spring.application.name=ruangkelas

# server 
server.port=8080
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure= true            
server.servlet.session.cookie.same-site= strict
server.servlet.session.cookie.name= APP_SESSION
server.servlet.session.cookie.max-age= 86400

# database 
# database 
spring.datasource.url=jdbc:mysql://ruangkelas.adrianz.me:3306/db-ruangkelas
spring.datasource.username=dev-ruangkelas
spring.datasource.password=K1tzex5$au74
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.core.env=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=azkiyafauzanengginering@gmail.com
spring.mail.password=htqw lznw hcnc saef
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true